// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Professionals_SeniorProject.DAL;

namespace The_Professionals_SeniorProject.Migrations
{
    [DbContext(typeof(AchievementContext))]
    [Migration("20181114012033_TheProfessionals")]
    partial class TheProfessionals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("The_Professionals_SeniorProject.Models.Schema.Accomplishment", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AchievementType");

                    b.Property<string>("Activity");

                    b.Property<string>("Author");

                    b.Property<string>("BookTitle");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("DateApproved");

                    b.Property<DateTime>("DateCompleted");

                    b.Property<DateTime>("DateStarted");

                    b.Property<string>("Description");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("JobTitle");

                    b.Property<string>("Provider");

                    b.Property<string>("URL");

                    b.Property<int?>("UserID");

                    b.HasKey("AchievementID");

                    b.HasIndex("UserID");

                    b.ToTable("Accomplishments");
                });

            modelBuilder.Entity("The_Professionals_SeniorProject.Models.Schema.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<bool>("IsSupervisor");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<int?>("SupervisorID");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("The_Professionals_SeniorProject.Models.Schema.Accomplishment", b =>
                {
                    b.HasOne("The_Professionals_SeniorProject.Models.Schema.User", "User")
                        .WithMany("Accomplishments")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
